### ISSUE TITLE
App freeze  and back button not working

### ISSUE THREAD

**Issue by kr-nahid** [T-Rex96/Easy_xkcd#133] opened 2018-05-26 22:03 UTC
#### Expected behavior
it shouldn't be freeze when searching a comics and user should be able to back when click on back button while in Updating database
#### Actual behavior
when i click on search option in Comics and searching new this app become freeze and back button not working for return to app

#### How to reproduce
* download the app and run it
* now click on search button and type new 
* note the bug and
* then click on back button and see the another bug

> Browser/App version: 6.0.4
 Operating system: android 6.0

#### Recording Of The Bug
https://www.youtube.com/watch?v=nZXC5WgQnQ4

**Comment by T-Rex96** [comment] 2018-05-27 18:18
Hey, thanks for the detailed bug report! I'm caught up in a lot of stuff right now so I probably won't be able to fix it right away. 
Can you provide logs for this bug? I unfortunately can't reproduce this on my device right now, might be a bug specific to your device or os version. Thanks!

**Comment by T-Rex96** [comment] 2018-11-05 15:46
Hey there, this should be fixed in the upcoming release, as I'm completely rewriting the App's database

**Closed** 2018-11-24 20:42 UTC
